# Generated by Django 3.2.5 on 2021-10-13 18:20

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from ..slugify import slugify

categories = [
    {
        'name': 'Baked',
        'name_uk': 'Запечені',
    },
    {
        'name': 'Classic',
        'name_uk': 'Класичні',
    },
    {
        'name': 'Felix',
        'name_uk': 'Фелікс',
    },
    {
        'name': 'Sweet',
        'name_uk': 'Солодкі',
    },
    {
        'name': 'Maki',
        'name_uk': 'Макі',
    },
    {
        'name': 'Dragon',
        'name_uk': 'Дракон',
    }
]

ingredients = [
    {
        'name': 'Butter',
        'name_uk': 'Вершкове масло',
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707415/ingredients_img/butter.png"),
    },
    {
        'name': 'Cucumber',
        'name_uk': 'Огірок',
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707415/ingredients_img/cucumber.png"),
    },
    {
        'name': 'Nori',
        'name_uk': 'Норі',
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707415/ingredients_img/nori.png"),
    },
    {
        'name': 'Rice',
        'name_uk': 'Рис',
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707415/ingredients_img/rice.png"),
    },
    {
        'name': 'Sesame',
        'name_uk': 'Кунжут',
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707415/ingredients_img/sesame.png"),
    }
]

sushi_items = [
    {
        'category': 2,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/philadelphia-salmon.png"),
        'name': 'Philadelphia with salmon',
        'name_uk': 'Філадельфія з лососем',
        'quantity': 320,
        'description': 'salmon, nori, cucumber, rice, cream cheese',
        'description_uk': 'лосось, норі, огірок, рис, сир вершковий',
        'price': 265,
        'discount': 0.0,
    },
    {
        'category': 1,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707427/sushi_img/baked-salmon.png"),
        'name': 'Baked salmon',
        'name_uk': 'Запечений лосось',
        'quantity': 350,
        'description': 'salmon, nori, rice, cream cheese, avocado, caviar, cheese cap',
        'description_uk': 'лосось, норі, рис, сир вершковий, авокадо, ікра, сирна шапочка',
        'price': 265,
        'discount': 0.0,
    },
    {
        'category': 2,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/philadelphia-acne.png"),
        'name': 'Philadelphia with acne',
        'name_uk': 'Філадельфія з вугрем',
        'quantity': 320,
        'description': 'nori, cucumber, rice, cream cheese, sesame seeds, unagi sauce, eel',
        'description_uk': 'норі, огірок, рис, сир вершковий, кунжут, соус унаги, вугор',
        'price': 335,
        'discount': 0.0,
    },
    {
        'category': 5,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/maki-salmon.png"),
        'name': 'Maki with salmon',
        'name_uk': 'Макі лосось',
        'quantity': 110,
        'description': 'salmon, nori, rice',
        'description_uk': 'лосось, норі, рис',
        'price': 105,
        'discount': 0.0,
    },
    {
        'category': 1,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/baked-acne.png"),
        'name': 'Baked acne',
        'name_uk': 'Запечений вугор',
        'quantity': 325,
        'description': 'nori, rice, cream cheese, sesame, eel, avocado, cheese cap',
        'description_uk': 'норі, рис, сир вершковий, кунжут, вугор, авокадо, сирна шапочка',
        'price': 315,
        'discount': 0.0,
    },
    {
        'category': 5,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/maki-tuna.png"),
        'name': 'Maki tuna',
        'name_uk': 'Макі тунець',
        'quantity': 320,
        'description': 'nori, rice, tuna',
        'description_uk': 'норі, рис, тунець',
        'price': 110,
        'discount': 0.0,
    },
    {
        'category': 4,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/sweet-bounty.png"),
        'name': 'Bounty',
        'name_uk': 'Баунті',
        'quantity': 255,
        'description': 'cream cheese, banana, coconut flakes, rice dough, coconut syrup',
        'description_uk': 'сир вершковий, банан, кокосова стружка, рисове тісто, кокосовий сироп',
        'price': 160,
        'discount': 0.0,
    },
    {
        'category': 6,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/dragon-green.png"),
        'name': 'Green dragon',
        'name_uk': 'Зелений дракон',
        'quantity': 310,
        'description': 'nori, rice, cream cheese, unagi sauce, avocado, shrimp, mango, mango-pineapple sauce',
        'description_uk': 'норі, рис, сир вершковий, cоус унаги, авокадо, креветка, манго, манго-ананасовий соус',
        'price': 290,
        'discount': 0.0,
    },
    {
        'category': 3,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/felix-salmon.png"),
        'name': 'Felix salmon',
        'name_uk': 'Фелікс лосось',
        'quantity': 330,
        'description': 'salmon, nori, rice, cream cheese, avocado, caviar, iceberg lettuce, shriracha sauce',
        'description_uk': 'лосось, норі, рис, сир вершковий, авокадо, ікра, салат айсберг, соус шрірача',
        'price': 270,
        'discount': 0.0,
    },
    {
        'category': 4,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/sweet-oreo.png"),
        'name': 'Oreo',
        'name_uk': 'Орео',
        'quantity': 285,
        'description': 'cream cheese, banana, nutella, oreo, rice dough, caramel topping',
        'description_uk': 'сир вершковий, банан, нутелла, орео, рисове тісто, карамельний топінг',
        'price': 180,
        'discount': 0.0,
    },
    {
        'category': 6,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/dragon-golden.png"),
        'name': 'Golden dragon',
        'name_uk': 'Золотий дракон',
        'quantity': 320,
        'description': 'nori, rice, unagi sauce, eel, tuna, avocado, caviar, japanese omega tamago',
        'description_uk': 'норі, рис, cоус унаги, вугор, тунець, авокадо, ікра, японський омлет тамаго',
        'price': 370,
        'discount': 0.0,
    },
    {
        'category': 3,
        'image': cloudinary.CloudinaryImage("https://res.cloudinary.com/sushi-store/image/upload/v1633707428/sushi_img/felix-acne.png"),
        'name': 'Felix acne',
        'name_uk': 'Фелікс вугор',
        'quantity': 295,
        'description': 'nori, rice, cream cheese, sesame, eel, avocado, caviar, iceberg lettuce, shriracha sauce, japanese omelette tamago',
        'description_uk': 'норі, рис, сир вершковий, кунжут, вугор, авокадо, ікра, салат айсберг, соус шрірача, японський омлет тамаго',
        'price': 300,
        'discount': 0.0,
    }
]


def load_data(apps, schema_editor):
    Sushi = apps.get_model("sushi", "Sushi")
    Category = apps.get_model("sushi", "Category")
    Ingredient = apps.get_model("sushi", "Ingredient")
    db_alias = schema_editor.connection.alias

    for category in categories:
        Category.objects.using(db_alias).create(
            category_name=category['name'],
            category_name_uk=category['name_uk'],
        )

    for ingredient in ingredients:
        Ingredient.objects.using(db_alias).create(
            name=ingredient['name'],
            name_uk=ingredient['name_uk'],
            image=ingredient['image'],
        )

    for sushi_item in sushi_items:
        Sushi.objects.using(db_alias).create(
            name=sushi_item['name'],
            name_uk=sushi_item['name_uk'],
            description=sushi_item['description'],
            description_uk=sushi_item['description_uk'],
            category=Category.objects.get(pk=sushi_item['category']),
            image=sushi_item['image'],
            quantity=sushi_item['quantity'],
            price=sushi_item['price'],
            discount=sushi_item['discount'],
        )

    s = Sushi.objects.get(pk=11)
    for ingredient in Ingredient.objects.all():
        s.ingredients.add(ingredient)


def create_slug(apps, schema_editor):
    Sushi = apps.get_model("sushi", "Sushi")
    for sushi_item in Sushi.objects.all():
        sushi_item.slug = slugify(sushi_item.name)
        sushi_item.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_name_uk', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uk', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='SetOfIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sushi.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uk', models.CharField(default='', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('description', models.TextField(default='')),
                ('description_uk', models.TextField(default='')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=6)),
                ('discount', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=3)),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='category', to='sushi.category')),
                ('ingredients', models.ManyToManyField(
                    through='sushi.SetOfIngredients', to='sushi.Ingredient')),
            ],
            options={
                'verbose_name_plural': 'Sushi',
            },
        ),
        migrations.AddField(
            model_name='setofingredients',
            name='sushi',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sushi.sushi'),
        ),
        migrations.RunPython(load_data),
        migrations.RunPython(create_slug)
    ]
