# Generated by Django 3.2.5 on 2021-08-08 19:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sushi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None, unique=True)),
                ('delivery_type', models.CharField(choices=[
                 ('P', 'Pickup'), ('D', 'Delivery')], default='D', max_length=1)),
                ('payment_method', models.CharField(choices=[
                 ('C', 'Cash'), ('D', 'Card')], default='С', max_length=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('I', 'In Process'), (
                    'D', 'Done'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('date_of_order', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='order.ordersushi')),
                ('sushi', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sushi.sushi')),
            ],
            options={
                'verbose_name_plural': 'Sushi Orders',
                'unique_together': {('order', 'sushi')},
            },
        ),
    ]
